[build]
  # Build command
  command = "npm run build"
  
  # Publish directory (Next.js output)
  publish = ".next"
  
  # Node.js version
  environment = { NODE_VERSION = "22" }

[build.environment]
  # Next.js environment variables
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules for Next.js SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API routes - ensure they use Node.js runtime
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"